version: 0.2

phases:
  install:
    commands:
      - node -v || (
          echo "Node.js not found. Installing Node.js 14...";
          curl -sL https://rpm.nodesource.com/setup_14.x | bash -;
          yum install -y nodejs;
        )
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Deployment to Elastic Beanstalk completed on `date`"

artifacts:
  files: '**/*'
  name: source

cache:
  paths:
    - node_modules/
