version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - node -v
      - if [[ $(node -v) != "v14"* ]]; then
          echo "Installing Node.js 14...";
          curl -sL https://deb.nodesource.com/setup_14.x | bash -;
          apt-get install -y nodejs;
        fi
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Deployment to Elastic Beanstalk completed on `date`"

artifacts:
  files: '**/*'
  name: source

cache:
  paths:
    - node_modules/
